spring:
   data:
      elasticsearch:
          cluster-name: es #默认为elasticsearch
          #cluster-nodes: 192.168.1.44:9330  #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
          properties:
              path:
                logs: ./elasticsearch/log #elasticsearch日志存储目录
                data: ./elasticsearch/data #elasticsearch数据存储目录



